#!/bin/sh
# Distros need to be imported into Beaker before we can provision them.

echo "This script will import distros into Beaker."
echo "The distros will not be mirrored locally."
echo "The following distros will be imported:"
echo " CentOS-5 x86_64"
echo " CentOS-5 i386"
echo " CentOS-6 x86_64"
echo " CentOS-6 i386"
echo " Fedora-16 x86_64"
echo " Fedora-16 i386"
echo " Fedora-17 x86_64"
echo " Fedora-17 i386"
echo -n "Do you want to proceed? (y/n) "
read answer
if [ "$answer" != "y" -a $answer != "Y" ]; then
    exit 1
fi

beaker-import http://mirror.centos.org/centos/5/os/x86_64/
beaker-import http://mirror.centos.org/centos/5/os/i386/
beaker-import http://mirror.centos.org/centos/6/os/x86_64/
beaker-import http://mirror.centos.org/centos/6/os/i386/
beaker-import http://download.fedoraproject.org/pub/fedora/linux/releases/17/Fedora/x86_64/os
beaker-import http://download.fedoraproject.org/pub/fedora/linux/releases/17/Fedora/i386/os
beaker-import http://download.fedoraproject.org/pub/fedora/linux/releases/16/Fedora/x86_64/os
beaker-import http://download.fedoraproject.org/pub/fedora/linux/releases/16/Fedora/i386/os

# This command will fetch the Beaker harness RPMs for all the distros which we
# have just imported. The harness must be mirrored locally on the Beaker server
# in order to run scheduled jobs.
beaker-repo-update

# And we're done!
echo "All Done!"
