name: Build docs

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: centos:7

    steps:
      - name: Fixup CentOS repo files
        run: |
          sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
          sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
          sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
      - name: Setup environment
        run: |
          yum install -y epel-release https://repo.ius.io/ius-release-el7.rpm
          yum install -y make nodejs git236-core
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: beaker-project.org
      - name: Checkout beaker repository
        uses: actions/checkout@v4
        with:
          repository: beaker-project/beaker
          path: beaker
          ref: 'master'
      - name: Install build dependencies
        run: |
          pushd beaker
          curl -o /etc/yum.repos.d/beaker-server.repo https://beaker-project.org/yum/beaker-server-RedHatEnterpriseLinux.repo
          yum-builddep beaker.spec -y

          # Hacks to get Sphinx LaTeX build working
          yum install -y python2-pip texlive texlive-*
          pip install sphinx==1.2.0
      - name: Build docs
        run: |
          cd beaker
          echo "html_theme_path = ['../../beaker-project.org/sphinx-theme']" >>documentation/conf.py

          PYTHONPATH=Common:Server:Client/src python -c '__requires__ = ["CherryPy < 3.0"]; import pkg_resources; execfile("/usr/bin/sphinx-build")' -b html -D html_theme=beaker -A branch_warning="$branch_warning" documentation documentation/_build/html
          PYTHONPATH=Common:Server:Client/src python -c '__requires__ = ["CherryPy < 3.0"]; import pkg_resources; execfile("/usr/bin/sphinx-build")' -b latex documentation documentation/_build/latex

          make -C documentation/_build/latex all-pdf

          mkdir documentation/tree
          cp -r documentation/_build/html/* documentation/tree/
          cp documentation/_build/latex/*.pdf documentation/tree/

      - name: Archive docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: beaker/documentation/tree/
